/** Every function fast-formula-parser (bundled by react-spreadsheet) implements. */
export const FORMULA_FUNCTION_NAMES: string[] = [
  "ABS", "ACCRINT", "ACOS", "ACOSH", "ACOT", "ACOTH", "ADDRESS", "AGGREGATE",
  "AND", "ARABIC", "AREAS", "ASC", "ASIN", "ASINH", "ATAN", "ATAN2", "ATANH",
  "AVEDEV", "AVERAGE", "AVERAGEA", "AVERAGEIF", "AVERAGEIFS", "BAHTTEXT",
  "BASE", "BESSELI", "BESSELJ", "BESSELK", "BESSELY", "BIN2DEC", "BIN2HEX",
  "BIN2OCT", "BITAND", "BITLSHIFT", "BITOR", "BITRSHIFT", "BITXOR", "CEILING",
  "CELL", "CHAR", "CHOOSE", "CLEAN", "CODE", "COLUMN", "COLUMNS", "COMBIN",
  "COMBINA", "COMPLEX", "CONCAT", "CONCATENATE", "CORREL", "COS", "COSH",
  "COT", "COTH", "COUNT", "COUNTIF", "CSC", "CSCH", "DATE", "DATEDIF",
  "DATEVALUE", "DAY", "DAYS", "DAYS360", "DBCS", "DEC2BIN", "DEC2HEX",
  "DEC2OCT", "DECIMAL", "DEGREES", "DELTA", "DEVSQ", "DOLLAR", "EDATE",
  "ENCODEURL", "EOMONTH", "ERF", "ERFC", "EVEN", "EXACT", "EXP", "FACT",
  "FACTDOUBLE", "FALSE", "FILTERXML", "FIND", "FINDB", "FISHER", "FISHERINV",
  "FIXED", "FLOOR", "FORECAST", "FREQUENCY", "GAMMA", "GAMMALN", "GAUSS",
  "GCD", "GEOMEAN", "GESTEP", "GROWTH", "HARMEAN", "HEX2BIN", "HEX2DEC",
  "HEX2OCT", "HLOOKUP", "HOUR", "IF", "IFERROR", "IFNA", "IFS", "IMABS",
  "IMAGINARY", "IMARGUMENT", "IMCONJUGATE", "IMCOS", "IMCOSH", "IMCOT",
  "IMCSC", "IMCSCH", "IMDIV", "IMEXP", "IMLN", "IMLOG10", "IMLOG2",
  "IMPOWER", "IMPRODUCT", "IMREAL", "IMSEC", "IMSECH", "IMSIN", "IMSINH",
  "IMSQRT", "IMSUB", "IMSUM", "IMTAN", "INDEX", "INFO", "INT", "INTERCEPT",
  "ISBLANK", "ISERR", "ISERROR", "ISEVEN", "ISLOGICAL", "ISNA", "ISNONTEXT",
  "ISNUMBER", "ISOWEEKNUM", "ISREF", "ISTEXT", "KURT", "LARGE", "LCM",
  "LEFT", "LEFTB", "LEN", "LENB", "LINEST", "LN", "LOG", "LOG10", "LOGEST",
  "LOWER", "MATCH", "MAX", "MAXA", "MAXIFS", "MDETERM", "MEDIAN", "MID",
  "MIDB", "MIN", "MINA", "MINIFS", "MINUTE", "MINVERSE", "MMULT", "MOD",
  "MONTH", "MROUND", "MULTINOMIAL", "MUNIT", "N", "NA", "NETWORKDAYS",
  "NOT", "NOW", "NUMBERVALUE", "OCT2BIN", "OCT2DEC", "OCT2HEX", "ODD",
  "OR", "PEARSON", "PERMUT", "PERMUTATIONA", "PHI", "PHONETIC", "PI",
  "POWER", "PRODUCT", "PROPER", "QUOTIENT", "RADIANS", "RAND", "RANDBETWEEN",
  "REPLACE", "REPLACEB", "REPT", "RIGHT", "RIGHTB", "ROMAN", "ROUND",
  "ROUNDDOWN", "ROUNDUP", "ROW", "ROWS", "RSQ", "SEARCH", "SEARCHB", "SEC",
  "SECH", "SECOND", "SERIESSUM", "SIGN", "SIN", "SINH", "SKEW", "SLOPE",
  "SMALL", "SQRT", "SQRTPI", "STANDARDIZE", "STDEVA", "STDEVPA", "STEYX",
  "SUBSTITUTE", "SUBTOTAL", "SUM", "SUMIF", "SUMIFS", "SUMPRODUCT", "SUMSQ",
  "SUMX2MY2", "SUMX2PY2", "SUMXMY2", "SWITCH", "T", "TAN", "TANH", "TEXT",
  "TEXTJOIN", "TIME", "TIMEVALUE", "TODAY", "TRANSPOSE", "TREND", "TRIM",
  "TRIMMEAN", "TRUE", "TRUNC", "TYPE", "UNICHAR", "UNICODE", "VLOOKUP",
  "WEBSERVICE", "WEEKDAY", "WEEKNUM", "WORKDAY", "XOR", "YEAR", "YEARFRAC",
];

/** Short descriptions for the functions people reach for most often. Everything
 * else in FORMULA_FUNCTION_NAMES still autocompletes, just without a blurb. */
export const FORMULA_FUNCTION_DESCRIPTIONS: Record<string, string> = {
  SUM: "Adds all the numbers in a range of cells.",
  AVERAGE: "Returns the average of a range of numbers.",
  COUNT: "Counts how many cells in a range contain numbers.",
  COUNTIF: "Counts cells in a range that match a condition.",
  SUMIF: "Adds cells in a range that match a condition.",
  SUMIFS: "Adds cells that match multiple conditions.",
  IF: "Returns one value if a condition is true, another if false.",
  IFS: "Checks multiple conditions and returns the value for the first true one.",
  IFERROR: "Returns a fallback value if a formula results in an error.",
  AND: "Returns TRUE if all conditions are true.",
  OR: "Returns TRUE if any condition is true.",
  NOT: "Reverses the logical value of its argument.",
  VLOOKUP: "Looks up a value in the first column of a range, returns from another column.",
  HLOOKUP: "Looks up a value in the first row of a range, returns from another row.",
  INDEX: "Returns a value from a range at a given row/column position.",
  MATCH: "Returns the position of a value within a range.",
  CONCATENATE: "Joins several text values into one.",
  CONCAT: "Joins several text values or ranges into one.",
  TEXTJOIN: "Joins text values with a delimiter, optionally skipping blanks.",
  TEXT: "Formats a number or date as text using a format code.",
  LEN: "Returns the number of characters in a text value.",
  LEFT: "Returns characters from the start of a text value.",
  RIGHT: "Returns characters from the end of a text value.",
  MID: "Returns characters from the middle of a text value.",
  TRIM: "Removes extra spaces from text.",
  LOWER: "Converts text to lowercase.",
  PROPER: "Capitalizes the first letter of each word.",
  ROUND: "Rounds a number to a given number of digits.",
  ROUNDUP: "Rounds a number up, away from zero.",
  ROUNDDOWN: "Rounds a number down, toward zero.",
  MIN: "Returns the smallest number in a range.",
  MAX: "Returns the largest number in a range.",
  ABS: "Returns the absolute value of a number.",
  TODAY: "Returns the current date.",
  NOW: "Returns the current date and time.",
  DATE: "Builds a date from year, month, and day values.",
};
